name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
          
          
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ljmf00/setup-lua@v.1.0.1  
    - name: setup-lua
      # You may pin to the exact commit or the version.
      # uses: ljmf00/setup-lua@3124df8c2dd6d93d88439bb3bf1211d5d9a0420e
      with:
        # version of Lua to setup
        lua-version: 5.4.4 # optional, default is 5.3.5
        # whether to install luarocks or not
        # install-luarocks: # optional, default is false
        # version of LuaRocks to setup
        # luarocks-version: # optional, default is 3.8.0
        # the target platform (e.g. -A Win32 | x64)
        # platform: # optional
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
